# Generated by Django 4.0.4 on 2022-06-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('Deleted', 'Deleted'), ('Overdue', 'Overdue')], max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('starting_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('do_data', models.DateTimeField(auto_now=True)),
                ('notify_me', models.BooleanField(default=True)),
                ('catagory', models.ManyToManyField(to='todo.catagory')),
            ],
        ),
    ]
