# Generated by Django 4.0.4 on 2022-06-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='task_image',
            field=models.ImageField(blank=True, null=True, upload_to='todo/image'),
        ),
    ]
