# Generated by Django 4.0.4 on 2022-06-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='do_data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='starting_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='updated_date',
            field=models.DateTimeField(),
        ),
    ]
