# Generated by Django 4.0.4 on 2022-06-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todo_do_data_alter_todo_starting_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
