# Generated by Django 4.0.4 on 2022-06-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todo_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='task_image',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='catagory',
        ),
        migrations.AddField(
            model_name='todo',
            name='catagory',
            field=models.CharField(default='Work', max_length=25),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Catagory',
        ),
    ]
