# Generated by Django 4.0.4 on 2022-06-02 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_remove_todo_status_todo_is_complited_todo_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_complited',
            new_name='is_completed',
        ),
    ]
